import {StyleSheet} from "react-native";

export const styles=StyleSheet.create({
	container:{
		backgroundColor:"#4369B0",
		alignItems:'center',
		height:'100%',
	},
	header:{
		height:100,
		flexDirection:'row',
		marginTop:175,
		justifyContent:'space-evenly',
	},
	f:{
		height:40,
		width:60,
		padding:30,
        marginLeft:-45,
	},
	textface:{
		fontSize:39,
		color:'#FFFFFF',
		fontWeight:'bold',
		fontFamily:'Roboto',
		marginLeft:16,
        marginTop:5,
	},
	Input:{
		marginVertical:18,
		width:'90%',
		backgroundColor:'#FFFFFF',
		height:50,
		paddingLeft:15,
	},
	texts:{
		alignItems:'center',
		justifyContent:'center',
		width:'90%',
	},
	login:{
		width:'90%',
		justifyContent:'center',
		alignItems:'center',
		height:48,
		backgroundColor:'#213873',
		paddingVertical:1,
	},
	textLogin:{
		textAlign:'center',
		color:'white',
		fontSize:20,
		fontWeight:'bold',
	},
	cadastrar:{
        //backgroundColor:"red",
		fontSize:18,
		marginVertical:30,
		color:'#FFFFFF',
		textDecorationLine:'underline',
	}
});